### ISSUE TITLE
Mulighet for å slette video

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMTVwp#1]

**Comment by mariusmandal** [comment]
Deaktiver video ved å lime inn url fra UKM-TV
Eksempelvis: http://tv.ukm.no/Har-du-en-historie/5697 skal deaktivere ID 5697
PSEUDO: UPDATE `ukm_tv_files` SET `deleted` = true WHERE `ID` = 5697

**Comment by mariusmandal** [comment]
Menyvalget UKM-TV må innføres i network admin, og derfra ha et dashbord, likt http://github.com/UKMNorge/UKMsupport.git gjør

**Comment by AsgeirSH** [comment]
Fixed slette video. UKMTV-dashboard flyttes til eget issue. Close.
