### ISSUE TITLE
Last ned fil fra TV-url

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMTVwp#3]
UKM Norge bør ha mulighet til å laste ned TV-filer.

Lim inn URL i input-felt, få ut 
- [x] direkte-lenke til bildefil
- [x] direkte-lenke til videofil (høyoppløselig)
- [x] samt plassering på dig.ark (path-beskrivelse, ikke link)

**Comment by AsgeirSH** [comment]
Fixed 2 av 3 (mulig du fikk sykt mange e-poster nå).

(Om file er høyoppløselig, hvis ikke er bare 1 av 3 fixed)

**Comment by mariusmandal** [comment]
Bytt ut ledetekst
"URLen må slutte med et skråstrek!"
med rtrim($path,'/').'/'; ?

**Comment by mariusmandal** [comment]
Digger GUI, men følgende testfil feiler da den ikke finner høyoppløselig fil (tenker da på _720p-filen) som TV.class skal klare å finne :)
http://tv.ukm.no/fylke/oslo/2016/7316-UKM-Oslo-gjr-DKS-show/

**Comment by mariusmandal** [comment]
dig.ark-path finnes ved å curl api.ukm:
http://api.ukm.no/video:info/$cron_id
http://api.ukm.no/video:info/11660 <- for testfilen
(path: dir / path:filename)

**Comment by AsgeirSH** [comment]
Dig.Ark-path feiler på enkelte, men ellers alt ok. Close!
