### ISSUE TITLE
Mulighet for å legge inn info-boks per person/innslag

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMTVwp#5]
Ref https://ukmnorge.freshdesk.com/helpdesk/tickets/1627

**Comment by mariusmandal** [comment]
Dette for å bygge en slags profil-side.
--
Jeg har nå gjort x, y og z etter denne filmen. Du kan se alle filmer av meg i UKM-TV her, eller du kan sjekke ut min nettside, hvor du kan se noe fra mine senere oppdrag / verk

**Comment by mariusmandal** [comment]
Flyttet i feature-system
